# Generated by Django 6.0.3 on 2026-03-14 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescentprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CHVNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('note', models.TextField()),
                ('chv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chvprofile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chv_notes', to='core.adolescentprofile')),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
    ]
