# Generated by Django 6.0.3 on 2026-03-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adolescentprofile_age_chvnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adolescentprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='adolescentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
