# Generated by Django 6.0.3 on 2026-03-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adolescentprofile_date_joined_chvprofile_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescentprofile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='chvprofile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
