# Generated by Django 6.0.3 on 2026-03-15 18:22

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adolescentprofile_last_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Nutrition', 'Nutrition & Diet'), ('Hygiene', 'Menstrual Hygiene'), ('Exercise', 'Physical Activity'), ('Mental Health', 'Emotional Wellbeing'), ('Anemia', 'Anemia Prevention')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
