# Generated by Django 6.0.3 on 2026-03-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_libraryresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryresource',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
